# version: "3.9"

services:
  backend:
    build: ./backend
    container_name: yts_backend
    ports:
      - "15000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - transmission

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - USER=admin
      - PASS=1234
      - PEERPORT=51413
      - TRANSMISSION_WEB_HOME=/config/web  # Carpeta personalizada para la UI
      - WATCH_DIR_ENABLED=false         # Deshabilitar directorio watch
    ports:
      - "19091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./downloads:/downloads
      - ./downloads/complete:/downloads/complete         # Directorio para descargas completadas
      - ./downloads/incomplete:/downloads/incomplete     # Directorio para descargas en progreso
      - ./downloads/movies:/downloads/movies             # Directorio para películas organizadas
      - ./transmission_config:/config
      - ./transmission-webhook:/usr/local/bin/transmission-webhook:ro  # Script webhook
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=America/Santiago
    volumes:
      - ./downloads/movies:/movies     # Plex lee las películas organizadas
      - ./plex_config:/config
    ports:
      - "32401:32400"
    restart: unless-stopped
